// <auto-generated />
using System;
using System.Collections.Generic;
using LetopiaPlatform.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LetopiaPlatform.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // --- Categories ---
            modelBuilder.Entity("LetopiaPlatform.Core.Entities.Category", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id");
                b.Property<string>("IconUrl").HasMaxLength(500).HasColumnType("character varying(500)").HasColumnName("icon_url");
                b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)").HasColumnName("name");
                b.Property<string>("Slug").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)").HasColumnName("slug");
                b.Property<string>("Type").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)").HasColumnName("type");
                b.HasKey("Id");
                b.HasIndex("Type").HasDatabaseName("ix_categories_type");
                b.HasIndex("Slug", "Type").IsUnique().HasDatabaseName("ix_categories_slug_type");
                b.ToTable("categories", (string)null);
            });

            // --- Channels ---
            modelBuilder.Entity("LetopiaPlatform.Core.Entities.Channel", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id");
                b.Property<bool>("AllowComments").ValueGeneratedOnAdd().HasDefaultValue(true).HasColumnName("allow_comments");
                b.Property<bool>("AllowMemberPosts").ValueGeneratedOnAdd().HasDefaultValue(true).HasColumnName("allow_member_posts");
                b.Property<string>("ChannelType").IsRequired().ValueGeneratedOnAdd().HasDefaultValue("Discussion").HasMaxLength(20).HasColumnName("channel_type");
                b.Property<Guid>("CommunityId").HasColumnType("uuid").HasColumnName("community_id");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                b.Property<string>("Description").HasMaxLength(500).HasColumnName("description");
                b.Property<int>("DisplayOrder").ValueGeneratedOnAdd().HasDefaultValue(0).HasColumnName("display_order");
                b.Property<bool>("IsArchived").ValueGeneratedOnAdd().HasDefaultValue(false).HasColumnName("is_archived");
                b.Property<bool>("IsDefault").ValueGeneratedOnAdd().HasDefaultValue(false).HasColumnName("is_default");
                b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnName("name");
                b.Property<Guid?>("ParentId").HasColumnType("uuid").HasColumnName("parent_id");
                b.Property<int>("PostCount").ValueGeneratedOnAdd().HasDefaultValue(0).HasColumnName("post_count");
                b.Property<string>("Slug").IsRequired().HasMaxLength(100).HasColumnName("slug");
                b.Property<DateTime>("UpdatedAt").HasColumnType("timestamp with time zone").HasColumnName("updated_at");
                b.HasKey("Id");
                b.HasIndex("CommunityId").HasDatabaseName("ix_channels_community_id");
                b.HasIndex("CommunityId", "ParentId", "Slug").IsUnique().HasDatabaseName("ix_channels_community_parent_slug");
                b.ToTable("channels", (string)null);
            });

            // --- Comments ---
            modelBuilder.Entity("LetopiaPlatform.Core.Entities.Comment", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id");
                b.Property<Guid>("AuthorId").HasColumnType("uuid").HasColumnName("author_id");
                b.Property<string>("Content").IsRequired().HasColumnType("text").HasColumnName("content");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                b.Property<bool>("IsDeleted").ValueGeneratedOnAdd().HasDefaultValue(false).HasColumnName("is_deleted");
                b.Property<Guid>("PostId").HasColumnType("uuid").HasColumnName("post_id");
                b.Property<DateTime>("UpdatedAt").HasColumnType("timestamp with time zone").HasColumnName("updated_at");
                b.Property<int>("Upvotes").ValueGeneratedOnAdd().HasDefaultValue(0).HasColumnName("upvotes");
                b.HasKey("Id");
                b.HasIndex("PostId").HasDatabaseName("ix_comments_post_id");
                b.ToTable("comments", (string)null);
            });

            // --- Communities ---
            modelBuilder.Entity("LetopiaPlatform.Core.Entities.Community", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id");
                b.Property<Guid>("CategoryId").HasColumnType("uuid").HasColumnName("category_id");
                b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnName("name");
                b.Property<string>("Slug").IsRequired().HasMaxLength(100).HasColumnName("slug");
                b.Property<bool>("IsActive").ValueGeneratedOnAdd().HasDefaultValue(true).HasColumnName("is_active");
                b.HasKey("Id");
                b.HasIndex("Slug").IsUnique().HasDatabaseName("ix_communities_slug");
                b.ToTable("communities", (string)null);
            });

            // --- Posts ---
            modelBuilder.Entity("LetopiaPlatform.Core.Entities.Post", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id");
                b.Property<Guid>("AuthorId").HasColumnType("uuid").HasColumnName("author_id");
                b.Property<Guid>("ChannelId").HasColumnType("uuid").HasColumnName("channel_id");
                b.Property<string>("Content").IsRequired().HasColumnType("text").HasColumnName("content");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                b.Property<string>("Title").IsRequired().HasMaxLength(200).HasColumnName("title");
                b.Property<int>("Upvotes").ValueGeneratedOnAdd().HasDefaultValue(0).HasColumnName("upvotes");
                b.HasKey("Id");
                b.HasIndex("ChannelId").HasDatabaseName("ix_posts_channel_id");
                b.ToTable("posts", (string)null);
            });

            // --- Reactions ---
            modelBuilder.Entity("LetopiaPlatform.Core.Entities.Reaction", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id");
                b.Property<DateTime>("CreatedAt").ValueGeneratedOnAdd().HasDefaultValueSql("CURRENT_TIMESTAMP").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                b.Property<string>("ReactionType").IsRequired().HasMaxLength(20).HasColumnName("reaction_type");
                b.Property<Guid>("TargetId").HasColumnType("uuid").HasColumnName("target_id");
                b.Property<string>("TargetType").HasMaxLength(50).HasColumnName("target_type");
                b.Property<Guid>("UserId").HasColumnType("uuid").HasColumnName("user_id");
                b.HasKey("Id");
                b.HasIndex("UserId", "TargetType", "TargetId").IsUnique().HasDatabaseName("ux_reactions_user_target");
                b.ToTable("reactions", (string)null);
            });

            // --- Projects ---
            modelBuilder.Entity("LetopiaPlatform.Core.Entities.Project", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id");
                b.Property<Guid>("CategoryId").HasColumnType("uuid").HasColumnName("category_id");
                b.Property<string>("Title").IsRequired().HasColumnName("title");
                b.Property<string>("Description").IsRequired().HasColumnName("description");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                b.Property<DateTime>("Deadline").HasColumnType("timestamp with time zone").HasColumnName("deadline");
                b.Property<int>("MaxMembers").ValueGeneratedOnAdd().HasDefaultValue(5).HasColumnName("max_members");
                b.Property<List<string>>("RequiredSkills").IsRequired().HasColumnType("text[]").HasColumnName("required_skills");
                b.Property<string>("Status").IsRequired().ValueGeneratedOnAdd().HasDefaultValue("Recruiting").HasMaxLength(20).HasColumnName("status");
                b.Property<Guid>("OwnerId").HasColumnType("uuid").HasColumnName("owner_id");
                b.HasKey("Id");
                b.HasIndex("OwnerId").HasDatabaseName("ix_projects_owner_id");
                b.ToTable("projects", (string)null);
            });

            // --- AspNet Identity Users ---
            modelBuilder.Entity("LetopiaPlatform.Core.Entities.Identity.User", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<string>("Email").HasMaxLength(256);
                b.Property<string>("UserName").HasMaxLength(256);
                b.Property<string>("Role").IsRequired().ValueGeneratedOnAdd().HasDefaultValue("Learner").HasColumnName("Role");
                b.HasKey("Id");
                b.ToTable("AspNetUsers", (string)null);
            });

            // --- Identity Relationship (UserRole) ---
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
            {
                b.Property<Guid>("UserId").HasColumnType("uuid");
                b.Property<Guid>("RoleId").HasColumnType("uuid");
                b.HasKey("UserId", "RoleId");
                b.ToTable("AspNetUserRoles", (string)null);
            });

#pragma warning restore 612, 618
        }
    }
}