using LetopiaPlatform.Core.Common;
using LetopiaPlatform.Core.Entities.Identity;
using LetopiaPlatform.Core.Enums;

namespace LetopiaPlatform.Core.Entities;

/// <summary>
/// Represents a learning roadmap generated by the agent.
/// </summary>
public class Roadmap : AuditableEntity
{
    /// <summary>
    /// Foreign key to the User who requested the roadmap.
    /// </summary>
    public Guid UserId { get; set; }

    /// <summary>
    /// Foreign key to the AgentConversation that generated the roadmap.
    /// </summary>
    public Guid ConversationId { get; set; }

    /// <summary>
    /// The title of the roadmap.
    /// </summary>
    public required string Title { get; set; }

    /// <summary>
    /// The learning topic or goal of the roadmap.
    /// </summary>
    public required string Topic { get; set; }

    /// <summary>
    /// A detailed description of the roadmap.
    /// </summary>
    public required string Description { get; set; }

    /// <summary>
    /// The current status of the roadmap.
    /// </summary>
    public RoadmapStatus Status { get; set; } = RoadmapStatus.Generating;

    /// <summary>
    /// Estimated duration in weeks to complete the roadmap.
    /// </summary>
    public int EstimatedDurationWeeks { get; set; }

    /// <summary>
    /// Navigation property to the User who created this roadmap.
    /// </summary>
    public User User { get; set; } = null!;

    /// <summary>
    /// Navigation property to the AgentConversation that generated this roadmap.
    /// </summary>
    public AgentConversation Conversation { get; set; } = null!;

    /// <summary>
    /// Collection of phases that make up this roadmap.
    /// </summary>
    public ICollection<RoadmapPhase> Phases { get; set; } = [];
}
